generate_sbom:
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  tags:
    - shared
  stage: build
  extends:
    - .rules:on_mr
  script:
    - trivy fs --format cyclonedx --output sbom.cdx.json .
  artifacts:
    paths:
      - sbom.cdx.json
    expire_in: 1 week